name: lmsalfa
description: 'LMS Smart rebuilt project'
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Hive local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.66.0
  collection: ^1.18.0

  # Core
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.0

  # Local database with Drift
  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.1.2
  path: ^1.9.0
  intl: ^0.18.1

  # File picker (mobile only usage)
  file_selector: ^1.0.3
  uuid: ^4.0.0

  http: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  drift_dev: ^2.13.0
  flutter_lints: ^6.0.0
  analyzer: ^6.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
# ✅ Prevent drift_dev from scanning your real code
targets:
  $default:
    builders:
      drift_dev:
        options:
          enabled: false


